# Generated by Django 5.2.8 on 2025-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
    ]
