# Generated by Django 5.2.8 on 2025-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
